# Generated by Django 2.2.3 on 2020-08-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=50, verbose_name='validator_name')),
                ('vehicle_id', models.CharField(max_length=80, verbose_name='vehicle_id')),
                ('user_id', models.CharField(max_length=80, verbose_name='user_id')),
            ],
            options={
                'ordering': ['-vehicle_id'],
            },
        ),
    ]
