# Generated by Django 2.2.3 on 2020-08-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, verbose_name='username')),
                ('name', models.CharField(default='noName', max_length=20, verbose_name='name')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('user_type', models.CharField(max_length=20, verbose_name='user_type')),
            ],
            options={
                'ordering': ['-password'],
            },
        ),
    ]
